# Generated by Django 2.1.2 on 2018-12-09 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'booking',
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='Current',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_no', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'current',
                'db_table': 'currents',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'equipment',
                'db_table': 'equipments',
            },
        ),
        migrations.CreateModel(
            name='EquipmentKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'equipment_kind',
                'db_table': 'equipment_kinds',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'group',
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Group')),
            ],
            options={
                'verbose_name_plural': 'group_user',
                'db_table': 'group_users',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('wide', models.IntegerField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'room',
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('prefecture', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('gps', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'studio',
                'db_table': 'studios',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('tel', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'user',
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Studio'),
        ),
        migrations.AddField(
            model_name='groupuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.User'),
        ),
        migrations.AddField(
            model_name='group',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.User'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.EquipmentKind'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Room'),
        ),
        migrations.AddField(
            model_name='current',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Studio'),
        ),
        migrations.AddField(
            model_name='current',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.User'),
        ),
        migrations.AddField(
            model_name='booking',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Group'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Room'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.User'),
        ),
    ]
