# Generated by Django 2.1.2 on 2018-12-25 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_logintoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_studio',
            field=models.BooleanField(default=False),
        ),
    ]
